# Generated by Django 3.2.16 on 2023-10-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0004_auto_20231027_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='price',
            field=models.FloatField(default=0.0, max_length=999.99),
        ),
    ]
